package com.xiaohei.mapper;

import com.xiaohei.model.Ch_Users;
import com.xiaohei.model.Ch_UsersExample;
import com.xiaohei.model.Ch_UsersKey;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface Ch_UsersMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ch_users
     *
     * @mbg.generated
     */
    long countByExample(Ch_UsersExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ch_users
     *
     * @mbg.generated
     */
    int deleteByExample(Ch_UsersExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ch_users
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Ch_UsersKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ch_users
     *
     * @mbg.generated
     */
    int insert(Ch_Users record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ch_users
     *
     * @mbg.generated
     */
    int insertSelective(Ch_Users record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ch_users
     *
     * @mbg.generated
     */
    List<Ch_Users> selectByExampleWithBLOBs(Ch_UsersExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ch_users
     *
     * @mbg.generated
     */
    List<Ch_Users> selectByExample(Ch_UsersExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ch_users
     *
     * @mbg.generated
     */
    Ch_Users selectByPrimaryKey(Ch_UsersKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ch_users
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") Ch_Users record, @Param("example") Ch_UsersExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ch_users
     *
     * @mbg.generated
     */
    int updateByExampleWithBLOBs(@Param("record") Ch_Users record, @Param("example") Ch_UsersExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ch_users
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") Ch_Users record, @Param("example") Ch_UsersExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ch_users
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Ch_Users record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ch_users
     *
     * @mbg.generated
     */
    int updateByPrimaryKeyWithBLOBs(Ch_Users record);
}