package com.xiaohei.mapper;

import com.xiaohei.model.Hy_jl;
import com.xiaohei.model.Hy_jlExample;
import com.xiaohei.model.Hy_jlKey;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface Hy_jlMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hy_jl
     *
     * @mbg.generated
     */
    long countByExample(Hy_jlExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hy_jl
     *
     * @mbg.generated
     */
    int deleteByExample(Hy_jlExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hy_jl
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Hy_jlKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hy_jl
     *
     * @mbg.generated
     */
    int insert(Hy_jl record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hy_jl
     *
     * @mbg.generated
     */
    int insertSelective(Hy_jl record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hy_jl
     *
     * @mbg.generated
     */
    List<Hy_jl> selectByExampleWithBLOBs(Hy_jlExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hy_jl
     *
     * @mbg.generated
     */
    List<Hy_jl> selectByExample(Hy_jlExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hy_jl
     *
     * @mbg.generated
     */
    Hy_jl selectByPrimaryKey(Hy_jlKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hy_jl
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") Hy_jl record, @Param("example") Hy_jlExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hy_jl
     *
     * @mbg.generated
     */
    int updateByExampleWithBLOBs(@Param("record") Hy_jl record, @Param("example") Hy_jlExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hy_jl
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") Hy_jl record, @Param("example") Hy_jlExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hy_jl
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Hy_jl record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hy_jl
     *
     * @mbg.generated
     */
    int updateByPrimaryKeyWithBLOBs(Hy_jl record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hy_jl
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Hy_jl record);
}