package com.xiaohei.mapper;

import com.xiaohei.model.Hy;
import com.xiaohei.model.HyExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface HyMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hy
     *
     * @mbg.generated
     */
    long countByExample(HyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hy
     *
     * @mbg.generated
     */
    int deleteByExample(HyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hy
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hy
     *
     * @mbg.generated
     */
    int insert(Hy record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hy
     *
     * @mbg.generated
     */
    int insertSelective(Hy record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hy
     *
     * @mbg.generated
     */
    List<Hy> selectByExample(HyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hy
     *
     * @mbg.generated
     */
    Hy selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hy
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") Hy record, @Param("example") HyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hy
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") Hy record, @Param("example") HyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hy
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Hy record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hy
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Hy record);
}