package com.xiaohei.mapper;

import com.xiaohei.model.Lc;
import com.xiaohei.model.LcExample;
import com.xiaohei.model.LcKey;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface LcMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lc
     *
     * @mbg.generated
     */
    long countByExample(LcExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lc
     *
     * @mbg.generated
     */
    int deleteByExample(LcExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lc
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(LcKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lc
     *
     * @mbg.generated
     */
    int insert(Lc record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lc
     *
     * @mbg.generated
     */
    int insertSelective(Lc record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lc
     *
     * @mbg.generated
     */
    List<Lc> selectByExampleWithBLOBs(LcExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lc
     *
     * @mbg.generated
     */
    List<Lc> selectByExample(LcExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lc
     *
     * @mbg.generated
     */
    Lc selectByPrimaryKey(LcKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lc
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") Lc record, @Param("example") LcExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lc
     *
     * @mbg.generated
     */
    int updateByExampleWithBLOBs(@Param("record") Lc record, @Param("example") LcExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lc
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") Lc record, @Param("example") LcExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lc
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Lc record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lc
     *
     * @mbg.generated
     */
    int updateByPrimaryKeyWithBLOBs(Lc record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lc
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Lc record);
}