package com.xiaohei.mapper;

import com.xiaohei.model.Tp;
import com.xiaohei.model.TpExample;
import com.xiaohei.model.TpKey;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TpMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp
     *
     * @mbg.generated
     */
    long countByExample(TpExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp
     *
     * @mbg.generated
     */
    int deleteByExample(TpExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(TpKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp
     *
     * @mbg.generated
     */
    int insert(Tp record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp
     *
     * @mbg.generated
     */
    int insertSelective(Tp record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp
     *
     * @mbg.generated
     */
    List<Tp> selectByExample(TpExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp
     *
     * @mbg.generated
     */
    Tp selectByPrimaryKey(TpKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") Tp record, @Param("example") TpExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") Tp record, @Param("example") TpExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Tp record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Tp record);
}