package com.xiaohei.mapper;

import com.xiaohei.model.Zbf;
import com.xiaohei.model.ZbfExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ZbfMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zbf
     *
     * @mbg.generated
     */
    long countByExample(ZbfExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zbf
     *
     * @mbg.generated
     */
    int deleteByExample(ZbfExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zbf
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String name);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zbf
     *
     * @mbg.generated
     */
    int insert(Zbf record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zbf
     *
     * @mbg.generated
     */
    int insertSelective(Zbf record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zbf
     *
     * @mbg.generated
     */
    List<Zbf> selectByExampleWithBLOBs(ZbfExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zbf
     *
     * @mbg.generated
     */
    List<Zbf> selectByExample(ZbfExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zbf
     *
     * @mbg.generated
     */
    Zbf selectByPrimaryKey(String name);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zbf
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") Zbf record, @Param("example") ZbfExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zbf
     *
     * @mbg.generated
     */
    int updateByExampleWithBLOBs(@Param("record") Zbf record, @Param("example") ZbfExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zbf
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") Zbf record, @Param("example") ZbfExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zbf
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Zbf record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zbf
     *
     * @mbg.generated
     */
    int updateByPrimaryKeyWithBLOBs(Zbf record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zbf
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Zbf record);
}