package com.xiaohei.model;

import java.util.Date;

public class Hy {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hy.ID
     *
     * @mbg.generated
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hy.name
     *
     * @mbg.generated
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hy.s_time
     *
     * @mbg.generated
     */
    private Date sTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hy.e_time
     *
     * @mbg.generated
     */
    private Date eTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hy.ID
     *
     * @return the value of hy.ID
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hy.ID
     *
     * @param id the value for hy.ID
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hy.name
     *
     * @return the value of hy.name
     *
     * @mbg.generated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hy.name
     *
     * @param name the value for hy.name
     *
     * @mbg.generated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hy.s_time
     *
     * @return the value of hy.s_time
     *
     * @mbg.generated
     */
    public Date getsTime() {
        return sTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hy.s_time
     *
     * @param sTime the value for hy.s_time
     *
     * @mbg.generated
     */
    public void setsTime(Date sTime) {
        this.sTime = sTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hy.e_time
     *
     * @return the value of hy.e_time
     *
     * @mbg.generated
     */
    public Date geteTime() {
        return eTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hy.e_time
     *
     * @param eTime the value for hy.e_time
     *
     * @mbg.generated
     */
    public void seteTime(Date eTime) {
        this.eTime = eTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hy
     *
     * @mbg.generated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        Hy other = (Hy) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getName() == null ? other.getName() == null : this.getName().equals(other.getName()))
            && (this.getsTime() == null ? other.getsTime() == null : this.getsTime().equals(other.getsTime()))
            && (this.geteTime() == null ? other.geteTime() == null : this.geteTime().equals(other.geteTime()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hy
     *
     * @mbg.generated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getName() == null) ? 0 : getName().hashCode());
        result = prime * result + ((getsTime() == null) ? 0 : getsTime().hashCode());
        result = prime * result + ((geteTime() == null) ? 0 : geteTime().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hy
     *
     * @mbg.generated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        Hy other = (Hy) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getName() == null ? other.getName() == null : this.getName().equals(other.getName()))
            && (this.getsTime() == null ? other.getsTime() == null : this.getsTime().equals(other.getsTime()))
            && (this.geteTime() == null ? other.geteTime() == null : this.geteTime().equals(other.geteTime()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hy
     *
     * @mbg.generated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getName() == null) ? 0 : getName().hashCode());
        result = prime * result + ((getsTime() == null) ? 0 : getsTime().hashCode());
        result = prime * result + ((geteTime() == null) ? 0 : geteTime().hashCode());
        return result;
    }
}