package com.xiaohei.model;

public class Hy_jlKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hy_jl.ID
     *
     * @mbg.generated
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hy_jl.jl_id
     *
     * @mbg.generated
     */
    private Integer jlId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hy_jl.ID
     *
     * @return the value of hy_jl.ID
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hy_jl.ID
     *
     * @param id the value for hy_jl.ID
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hy_jl.jl_id
     *
     * @return the value of hy_jl.jl_id
     *
     * @mbg.generated
     */
    public Integer getJlId() {
        return jlId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hy_jl.jl_id
     *
     * @param jlId the value for hy_jl.jl_id
     *
     * @mbg.generated
     */
    public void setJlId(Integer jlId) {
        this.jlId = jlId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hy_jl
     *
     * @mbg.generated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        Hy_jlKey other = (Hy_jlKey) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getJlId() == null ? other.getJlId() == null : this.getJlId().equals(other.getJlId()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hy_jl
     *
     * @mbg.generated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getJlId() == null) ? 0 : getJlId().hashCode());
        return result;
    }


}