package com.xiaohei.model;

public class Tp extends TpKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tp.px
     *
     * @mbg.generated
     */
    private Boolean px;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tp.px
     *
     * @return the value of tp.px
     *
     * @mbg.generated
     */
    public Boolean getPx() {
        return px;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tp.px
     *
     * @param px the value for tp.px
     *
     * @mbg.generated
     */
    public void setPx(Boolean px) {
        this.px = px;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp
     *
     * @mbg.generated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        Tp other = (Tp) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getUserId() == null ? other.getUserId() == null : this.getUserId().equals(other.getUserId()))
            && (this.getTpId() == null ? other.getTpId() == null : this.getTpId().equals(other.getTpId()))
            && (this.getPx() == null ? other.getPx() == null : this.getPx().equals(other.getPx()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp
     *
     * @mbg.generated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getUserId() == null) ? 0 : getUserId().hashCode());
        result = prime * result + ((getTpId() == null) ? 0 : getTpId().hashCode());
        result = prime * result + ((getPx() == null) ? 0 : getPx().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp
     *
     * @mbg.generated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        Tp other = (Tp) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getUserId() == null ? other.getUserId() == null : this.getUserId().equals(other.getUserId()))
            && (this.getTpId() == null ? other.getTpId() == null : this.getTpId().equals(other.getTpId()))
            && (this.getPx() == null ? other.getPx() == null : this.getPx().equals(other.getPx()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp
     *
     * @mbg.generated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getUserId() == null) ? 0 : getUserId().hashCode());
        result = prime * result + ((getTpId() == null) ? 0 : getTpId().hashCode());
        result = prime * result + ((getPx() == null) ? 0 : getPx().hashCode());
        return result;
    }
}